# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-20 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0002_auto_20170511_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss', to='Enterprise.Employee'),
        ),
    ]
