# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0008_auto_20170623_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.IntegerField(default=13201892),
        ),
    ]
