# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0021_auto_20170713_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.IntegerField(default=13201849),
        ),
    ]
