# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_auto_20170511_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Baja', max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='prioridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.ServicePriority'),
        ),
    ]
