# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_auto_20170528_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='notification_boss',
            field=models.BooleanField(default=False),
        ),
    ]
