# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_auto_20170624_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.Category'),
        ),
    ]
