# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0007_auto_20170624_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='n_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='n_status',
            field=models.BooleanField(default=True),
        ),
    ]
