# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-20 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0002_auto_20170511_2307'),
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_solution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ticket.Ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.Employee'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
