# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0006_auto_20170617_1924'),
        ('Ticket', '0003_auto_20170521_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.Technical'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solution',
            field=models.TextField(default=''),
        ),
    ]
