# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0008_auto_20170630_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(default=310),
        ),
    ]
