# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0009_auto_20170701_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(default=933),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Service.Service'),
        ),
    ]
