# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0017_auto_20170701_0836'),
        ('Ticket', '0010_auto_20170701_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='was_attended',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enterprise.Technical'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(default=352),
        ),
    ]
