# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0013_auto_20170701_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(default=919),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
