# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0014_auto_20170709_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 13, 19, 55, 10, 394877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(default=387),
        ),
    ]
