# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0015_auto_20170713_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(default=597),
        ),
    ]
